name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Show recent commits
        run: git log --oneline -n 10
      - name: Determine which Dockerfiles changed
        id: detect
        run: |
          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Dockerfile$' || true)
          root_changed=false
          sub_paths=()

          while IFS= read -r file; do
            if [[ "$file" == "Dockerfile" ]]; then
              root_changed=true
            elif [[ "$file" =~ ^([^/]+)/Dockerfile$ ]]; then
              sub_paths+=("${BASH_REMATCH[1]}")
            fi
          done <<< "$changed"

          # If root changed, add all subdirs (build all)
          if $root_changed; then
            sub_paths=()
            for d in */; do
              if [ -f "${d}Dockerfile" ]; then
                sub_paths+=("${d%/}")
              fi
            done
          fi

          echo "root_changed=$root_changed" | tee -a $GITHUB_OUTPUT
          echo "sub_paths=$(jq -c -n '$ARGS.positional' --args "${sub_paths[@]}")" | tee -a $GITHUB_OUTPUT

    outputs:
      root_changed: ${{ steps.detect.outputs.root_changed }}
      sub_paths: ${{ steps.detect.outputs.sub_paths }}

  build-root:
    needs: detect
    if: needs.detect.outputs.root_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build root Dockerfile
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_REPO }}:latest

  build-sub:
    needs: [detect, build-root]
    if: always() && join(fromJson(needs.detect.outputs.sub_paths || '[]'), '') != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJson(needs.detect.outputs.sub_paths) }}
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build sub Dockerfile
        uses: docker/build-push-action@v5
        with:
          file: ./${{ matrix.target }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.target }}:latest
